#!/bin/bash

set -ouex pipefail

# Remove unneeded repositories and update
rm -f /etc/apt/apt.conf.d/docker-gzip-indexes /etc/apt/apt.conf.d/docker-no-languages
rm -f /var/log/apt/eipp.log.xz
apt update -y

# Required packages
apt install -y \
  btrfs-progs \
  ca-certificates \
  curl \
  dracut \
  dosfstools \
  e2fsprogs \
  fdisk \
  firmware-linux-free \
  iproute2 \
  iputils-ping \
  linux-image-generic \
  skopeo \
  systemd \
  systemd-boot-* \
  xfsprogs \
  zstd

# Build Initramfs
KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")"
dracut --force --no-hostonly --reproducible --zstd --verbose \
  --kver "$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"
cp "/boot/vmlinuz-$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/vmlinuz"

# Use proper home directory for new users
sed -i 's|.*HOME=/home|HOME=/var/home|' "/etc/default/useradd"

# Enable boot.mount explicitly
systemctl enable boot.mount
systemctl enable home.mount
systemctl enable root.mount
systemctl enable srv.mount
systemctl enable mnt.mount

# remove /etc/machine-id
rm -f /etc/machine-id
