#!/bin/bash

set -ouex pipefail

# Remove unneeded repositories and update
rm -f /etc/apt/apt.conf.d/docker-gzip-indexes /etc/apt/apt.conf.d/docker-no-languages
apt update -y

# Required packages
apt install -y \
  dracut \
  btrfs-progs \
  dosfstools \
  e2fsprogs \
  fdisk \
  firmware-linux-free \
  linux-image-generic \
  skopeo \
  systemd \
  systemd-boot \
  systemd-boot-* \
  xfsprogs

# Oxidize
apt install -y \
  sudo-rs \
  rust-coreutils

# Build Initramfs
KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")"
dracut --force --no-hostonly --reproducible --zstd --verbose \
  --kver "$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"
cp "/boot/vmlinuz-$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/vmlinuz"

# Use proper home directory for new users
sed -i 's|.*HOME=/home|HOME=/var/home|' "/etc/default/useradd"
